language: python
python:
  - 2.6
  - 2.7
  - pypy
  - 3.3
  - 3.4
  - 3.5

before_install:
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install nodejs
  - ls /usr/bin/no*

# command to install dependencies
install:
  - travis_retry pip install coverage nose2 
  - python setup.py develop

# command to run tests
script:
  - if [[ $TRAVIS_PYTHON_VERSION != 3* ]]; then nose2 -c unittest-python2.cfg; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then nose2 -c unittest-python3.cfg; fi
