language: python
python:
  - 2.6
  - 2.7
  - pypy
  - 3.3
  - 3.4

before_install:
  - sudo apt-get update
  - sudo apt-get install nodejs
  - ls /usr/bin/no*

# command to install dependencies
install: "python setup.py develop"

# command to run tests
script: "python setup.py test"
